### ISSUE TITLE
Request: better error message on failed parsing `pypackage.meta`

### ISSUE THREAD

**Issue by Zearin** [ccpgames/pypackage#11]
Something <del>is</del><ins>was</ins> screwing parsing my `pypackage.meta` file.  

The error message was:

```
Error reading json from /Users/«…path/to/project…»/pypackage.meta: JSONDecodeError("Expecting ',' delimiter: line 32 column 11 (char 673)",)
```

However, that line had no errors.  (Presumably, this is because I have a lot of comments in my `pypackage.meta`, which are removed before parsing the file as JSON.)

Eventually, I discovered the problem by pasting the file contents into a blank editor and removing all the comments.  

From a usability perspective, I would have wanted pypackage to spit out the JSON—well, it was malformed, so let’s call it “not-quite-JSON”—that it was *attempting* to parse when it choked.  That would have allowed me to find the problem in seconds instead of minutes.

**Comment by a-tal** [comment]
hey, thanks for brining this up. 0.2.3 will include the original line in the meta if the json fails to parse.
