### ISSUE TITLE
License not being populated

### ISSUE THREAD

**Issue by Zearin** [ccpgames/pypackage#12]
**NOTE:** I discovered this issue while working on a repo that is (temporarily) private.  I’ve added @a-tal to the list of contributors to allow you to view the repository and investigate this bug.  The commit where I discovered the bug is [eb2224b6](https://github.com/Zearin/cucumber-python/commit/eb2224b6907b87665cb715bbc5dd426b37b34499).

----

# Description

When I run `py-build` and inspect the `*.egg-info` contents, some of the metadata is wrong.  For this Issue, let’s focus on the `License` (or `license`).

I have specified a `license` in my `pypackage.meta`, but in the `*.egg-info/PKG-INFO` file, the license is listed as `UNKNOWN`.  (If pypackage also tries to guess from repo files, I also have a root-level `LICENSE` file with the standard MIT License text.)

# To Reproduce the Issue

- Check out [eb2224b6](https://github.com/Zearin/cucumber-python/commit/eb2224b6907b87665cb715bbc5dd426b37b34499)
- Run `python3 -m venv _venv` (at least, that’s the venv name I’ve chosen)
- Run `source _venv/bin/activate`
- Run `py-build` 
- Check `src/cucumber.egg-info/PKG-INFO` for `License: UNKNOWN`

**Comment by a-tal** [comment]
hey,

thank you for the very clear report, access to the repo, and reproduction steps.

was able to quickly find this oversight, and have included license into the std attribute section. `0.2.5` includes these changes.

**Comment by Zearin** [comment]
Awesome!  You rock!  :)

I am really enjoying the `pypackage` way of managing my project.  The fact that you are fixing bugs so quickly after I report them is making me so happy, because I actually have hope for a non-painful future of Python packaging.  

Thank you!!!

**Comment by Zearin** [comment]
One last comment…

Earlier you thanked me for a “very clear report”.  

If you like the way I formatted that report, you can [add a template for GitHub Issues](https://github.com/blog/2111-issue-and-pull-request-templates).  

Here’s an excerpt with the important details:

>To add an Issue template to a repository create a file called `ISSUE_TEMPLATE` in the root directory. A file extension is optional, but Markdown files (`.md`) are supported. Markdown support makes it easy to add things like headings, links, @-mentions, and task lists to your templates.
> 
> Pull Request templates follows the same pattern: add a file called `PULL_REQUEST_TEMPLATE` to the root directory of your repository.
> 
> If you're worried about the added clutter in the root directory of your project, we also added support for a `.github/` folder. You can put `CONTRIBUTING.md`, `ISSUE_TEMPLATE.md`, and `PULL_REQUEST_TEMPLATE.md` files in `.github/` and everything will work as expected.

**Comment by Zearin** [comment]
(Forgot to explicitly describe the following…)

If you add those files, then every time someone creates (for example) a new Issue, then the issue will be pre-populated with the contents of your Issue template.  

It’s not enforced, but it can be a strong encouragement to format Issues (or Pull Requests, etc.) in the way that is most useful to **you**.

☻

**Comment by a-tal** [comment]
hmm. that's really neat... didn't know about that feature. thanks for the info, will try to put something together for that :+1:
