### ISSUE TITLE
Offer command to undo installation of `py-develop`

### ISSUE THREAD

**Issue by Zearin** [ccpgames/pypackage#17]
I hadn’t been using `py-develop`, so I gave it a try:

- I ran `py-develop` (it worked fine)
- I realized there is no command to undo the effects of `py-develop`
- I attempted to do so manually:
    - (with virtual env active) I ran `pip3 uninstall -y «package»` and got the following error:

```
    Exception:
    Traceback (most recent call last):
      File "/…/«project»/_venv/lib/python3.5/site-packages/pip/basecommand.py", line 209, in main
        status = self.run(options, args)
      File "/…/«project»/_venv/lib/python3.5/site-packages/pip/commands/uninstall.py", line 76, in run
        requirement_set.uninstall(auto_confirm=options.yes)
      File "/…/«project»/_venv/lib/python3.5/site-packages/pip/req/req_set.py", line 326, in uninstall
        req.uninstall(auto_confirm=auto_confirm)
      File "/…/«project»/_venv/lib/python3.5/site-packages/pip/req/req_install.py", line 691, in uninstall
        '(at %s)' % (link_pointer, self.name, dist.location)
    AssertionError: Egg-link /…/«project»/src does not match installed location of cucumber (at /…/«project»/_venv/lib/python3.5/site-packages)
```

**Comment by a-tal** [comment]
yeah, this is a problem with `python setup.py develop` as well. will try to come up with something

**Comment by Zearin** [comment]
Oh, okay.  I had no idea!  Somehow I’ve always managed to avoid using `python setup.py develop`, but I was curious about the simpler `py-develop` command, so I gave it a shot.

**Comment by Zearin** [comment]
(How did a language as wonderful as Python ever end up with such a tangled *hell* for packaging?!?)

**Comment by a-tal** [comment]
yeah, I dunno. what you could do as well though, after running `py-develop`, either install the output of `py-build` or run `py-install`, then you could uninstall with pip.

shouldn't be too much to make a better uninstall for develop-mode packages though

**Comment by Zearin** [comment]
Well, the direction of pypackage is up to you.  I think I will go back to avoiding “develop” mode…I seemed to get along just fine without it!

**Comment by a-tal** [comment]
this is fixed now. you can run `py-develop --uninstall` and it will remove the pth file
