### ISSUE TITLE
Support `src/<project>/` directory layout

### ISSUE THREAD

**Issue by Zearin** [ccpgames/pypackage#6]
Can you make pypackage support a directory layout where the Python package is under `src/«project name»/`?  

I have always preferred this approach, but someone wrote [an excellent article](https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure) describing the benefits of structuring projects this way.

**Comment by a-tal** [comment]
I'm sorry but I have to take a hard stance against this. The `src` directory is not pythonic. You can structure you project like this if you wish, and modify the `packages`, `package_dir` and/or `py_modules` keys to search under `src` if you like. I wouldn't recommend doing that though. Several of the points brought up in that article are a by-products of this unpythonic behavior and/or baseless (forcing testing against installed version for instance, you're really just some path muckery away when nested under src, hardly impossible).

As a further point, the package name `src` is a perfectly valid. Differentiating modules in the package `src` verses modules that live in a subfolder `src` would be impossible.
