### ISSUE TITLE
Mysterious author_email being populated

### ISSUE THREAD

**Issue by Zearin** [ccpgames/pypackage#8]
I was testing using `py-test`.  This generated an `*.egg-info/` directory alongside my source package.  In  `*.egg-info/PKG-INFO`, there is a value for `Author-email:`, even though I provided none in my `pypackage.meta`.

This mysterious author's email is (spam-escaped) eric [ at-sign ] ionrock [ dot ] org.  

Do you know where it is coming from…?

**Comment by a-tal** [comment]
somewhere in `__init__.py`, `__version__.py` or `version.py` there's something like `email = "that address"`

pypackage guesses at a bunch of package details if you let it; check out the [guessing module](https://github.com/ccpgames/pypackage/blob/master/pypackage/guessing.py), or the specific [function for authors and emails](https://github.com/ccpgames/pypackage/blob/master/pypackage/guessing.py#L84)

**Comment by Zearin** [comment]
Okay, I’ve discovered it:

```
$ ag --all-text --literal 'eric@' ./
_venv/lib/python3.5/site-packages/pip/_vendor/cachecontrol/__init__.py
6:__email__ = 'eric@ionrock.org'
```

So, the email field was being populated out of one of pip’s sub packages living in my virtual environment dir (`_venv/`).

So:

- Why is pypackage looking in my virtual environment dir as part of the guessing process?  
- How can I tell it to ignore `_venv/`?

**Comment by a-tal** [comment]
fair enough, that's not my workflow but I can respect it. I've added `.?venv` to the ignore dir patterns. 0.2.1 includes this.

adding configurable ignore patterns could be a thing, but would take a bit more time to implement.
