### ISSUE TITLE
py-clean command?

### ISSUE THREAD

**Issue by Zearin** [ccpgames/pypackage#9]
Would a `py-clean` command be possible?  

**Rationale:** To clean the generated `setup.py`, `*.egg-info`, etc. files; to restore a project to the state it was before invoking any `py-*` commands.

**Comment by a-tal** [comment]
yeah. I have a bash alias to do this atm. can turn it into something a little better if I can find some time

**Comment by a-tal** [comment]
added in 0.2.4
